# Generated by Django 4.1.5 on 2024-06-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_store_path', models.CharField(max_length=255)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.document')),
            ],
        ),
    ]
