# Generated by Django 5.0.6 on 2024-06-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_processeddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
