# Generated by Django 5.0.6 on 2024-06-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_document_processed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="processeddocument",
            old_name="vector_store_path",
            new_name="collection_name",
        ),
    ]
