# Generated by Django 4.1.5 on 2024-07-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('founding_yr', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Employees', models.CharField(max_length=100)),
                ('Followers', models.CharField(max_length=100)),
                ('Engagement', models.CharField(max_length=100)),
                ('Revenue', models.CharField(max_length=100)),
                ('Users', models.CharField(max_length=100)),
                ('Trademarks', models.IntegerField()),
                ('Funding', models.IntegerField()),
            ],
        ),
    ]
