# Generated by Django 4.1.5 on 2024-07-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_companies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
