# Generated by Django 5.0.1 on 2024-07-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='defined_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
    ]
