# Generated by Django 5.0.1 on 2024-10-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_defined_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
